### ISSUE TITLE
Big O Notation Chapter Issues - 3rd Edition EPUB

### ISSUE THREAD

**Issue by Causaelity** [waynewbishop/SwiftStructures#111]
In the making comparisons chapter you define a number list:

`let numberList : Array<Int> = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

This works fine for the Linear Time solution, however since the binarySearch function is flagged as a mutating function, the compiler will complain that you cannot use a mutating member on an immutable value.

Either numberList can be made a var, or since the binarySearch function never mutates its contents, could be updated appropriately.  

At the end of the chapters in the Further Reading section, 3 of the 4 links are bad or point to the incorrect site.

**Comment by waynewbishop** [comment]
Thanks @Causaelity! This issue will be resolved in a soon-to-be-released book update.
