### ISSUE TITLE
Basic Sorting Issues - 3rd Edition EPUB

### ISSUE THREAD

**Issue by Causaelity** [waynewbishop/SwiftStructures#113]
In the further reading section the following links are bad:

1. Invariant
2. Insertion Sort

OCD red flag:
In the Bubble Sort you use primaryIndex and secondaryIndex (yes!)
however in the other two sorts you use: pimaryindex and secondaryindex.  Please be consistent in the same chapter.

**Comment by waynewbishop** [comment]
Thanks @Causaelity! This issue will be resolved in a soon-to-be-released book update.
