### ISSUE TITLE
Extend Sorting Algorithms as Array Extension?

### ISSUE THREAD

**Issue by waynewbishop** [waynewbishop/SwiftStructures#15]
Sorting is one of most popular essays at www.waynewbishop.com. As part of this I would like refactor the article to include the newly added examples of Quick Sort and Merge Sort. The essay illustrations should also be redone or removed.

www.waynewbishop.com/swift/sorting-algorithms

**Comment by acegreen** [comment]
@waynewbishop thanks for the great articles on those various topics. I'll be purchasing the book. In the meantime I rewrote the bubbleSort() function as the current implementation on your site was not fully sorting it out. 

```
func bubbleSort() -> [Generator.Element] {

        // check for trivial case
        guard self.count > 1 else {
            return self
        }
        
        // mutated copy
        var output = self
        var count = self.count
        
        repeat {
    
            for index in 0..<count - 1 {
                
                let key = output[index]
                
                // compare/swap positions
                if key > output[index + 1] {
                    swap(&output[index], &output[index + 1])
                }
            }
            count--
            
        } while count > 0
        
        return output
    }

```

**Comment by waynewbishop** [comment]
Hi Ace, thanks for your interest in the book and for reviewing these algorithms! I do like some of these improvements and also notice a chance to enhance the corresponding unit tests. I'll keep this issue open until I get a chance to address the potential enhancements. 

`https://github.com/waynewbishop/SwiftStructures/blob/master/SwiftTests/SortingTest.swift`

**Comment by waynewbishop** [comment]
Done.
