### ISSUE TITLE
Please publish your licensing terms.

### ISSUE THREAD

**Issue by adonoho** [waynewbishop/SwiftStructures#16]
Mr. Bishop,

It looks like you have a fine library here. I cannot use it without understanding the terms under which it is licensed. Could you clarify your intentions by publishing your terms?

Anon,
Andrew

**Comment by waynewbishop** [comment]
Hi Andrew;

Thanks for reviewing the project and bringing this up. New licensing terms have been added to the project. For more just review the new <b>license.md</b> file. 

Regards;

-Wayne
