### ISSUE TITLE
Remove "times" integer extension

### ISSUE THREAD

**Issue by waynewbishop** [waynewbishop/SwiftStructures#26]
Hi Richard;

Just making some notes. When refactoring the merge sort it looks like we can also remove this extension as well. 

```
extension Int {
	
    //iterates the closure body a specified number of times
	func times(closure:(Int)->Void) {
		for i in 0...self {
			closure(i)
		}
	}
	
}
```

**Comment by waynewbishop** [comment]
After review this I've decided to keep this in the code as is. It's a really neat function that could be utilized in other areas.

**Comment by voidet** [comment]
Great :)
