### ISSUE TITLE
Let be friends

### ISSUE THREAD

**Issue by EvgenyKarkan** [waynewbishop/SwiftStructures#32]
Hi! 
Check out my repo with same stuff in Objective-C.
https://github.com/EvgenyKarkan/EKAlgorithms
I will be glad if you mention it in your Readme ;)

**Comment by waynewbishop** [comment]
Hi Evgeny;

Thanks for reaching out and the update! I appreciate the link you've added for SwiftStructures to your own project. As a result, I've added a link to your project a new section of my ```readme.md``` file. I've also started following you on twitter in case you have any questions.

Regards;

-Wayne

**Comment by EvgenyKarkan** [comment]
Cool, Thank you Wayne! 
I also started following you on twitter. 
My tweets are about ios development mostly, sometimes I share rock music bands, no spam :)
Have a nice day!
