### ISSUE TITLE
swift cannot invoke initializer for generic type with no arguments

### ISSUE THREAD

**Issue by ACChe** [waynewbishop/SwiftStructures#34]
In this post (http://waynewbishop.com/swift/stacks-queues), I have a question on the code in "Enqueuing Objects",  
```
public class Queue<T> { 
    private var top: QNode<T>! = QNode<T>() 
    //enqueue the specified object 
     func enQueue(var key: T) {
    //check for the instance 
    if (top == nil) { 
        top = QNode() 
} - See more at: http://waynewbishop.com/swift/stacks-queues#sthash.ipvM9iug.dpuf
```
While create a generic type QNode(), seems it should be write the type to be within angle brackets. But here is pass nothing without any compile error? So what brought this on?

**Comment by waynewbishop** [comment]
Hi Cam;

Good find with this issue. Turns out this was a HTML typo on the website. This has since been corrected and also confirmed with the corresponding ```Queue.swift``` file. 

Thanks!
