### ISSUE TITLE
Redundant / Unnecessary Parentheses

### ISSUE THREAD

**Issue by hoke-t** [waynewbishop/SwiftStructures#39]
In Swift, parentheses in loops / control structures are optional. They often times make readability easier, but in some cases can also overly complicate the code. It is up to you whether you want to use them or not, but there are a couple of places in this project in which I feel they could be removed. Here is an example:

In ```Source/Factories/LinkedList.swift```:

```swift
//the number of items
    var count: Int {
        
            if (head.key == nil) {
                return 0
            }
                
            else  {
                
                var current: LLNode = head
                var x: Int = 1
                
                
                //cycle through the list of items
                while ((current.next) != nil) {
                    current = current.next!
                    x++
                }
                
                return x
                
            }
    }
```
I think that we could change the code, for example in the if statement, to be:

```swift
var count: Int {
        
            if head.key == nil {
                return 0
            }
```

and in the while loop:

```swift
//cycle through the list of items
                while current.next != nil {
                    current = current.next!
                    x++
                }
```

Again, up to you, the author, but I think it could help Swift learners looking at this code to recognize some of the readability features of Swift versus Objective-C.

**Comment by waynewbishop** [comment]
Hi Tanner;

Thanks for bringing up this great point. I was planning on mentioning the optional use of parentheses with my next essay on closures, but it would be worth noting this with the existing code base. If there are other areas you feel should / could be updated, feel free to send along the filename and line numbers and I can take a look.

**Comment by waynewbishop** [comment]
I've made a number of revisions throughout code to remove extra parentheses. As discussed, this has made the code more readable.
