### ISSUE TITLE
Update ReadeME.md BFS example to Swift 2.0

### ISSUE THREAD

**Issue by waynewbishop** [waynewbishop/SwiftStructures#54]
- Make any required changes to this example. 
- Find related method in source code and update example.

**Comment by hoke-t** [comment]
I made a <a href="https://github.com/waynewbishop/SwiftStructures/pull/55"> pull request</a>.

**Comment by waynewbishop** [comment]
Hi Tanner;

Thanks again for looking into this. Here's a link to the updated file for Swift 2.0

https://github.com/waynewbishop/SwiftStructures/blob/swift-2.0/README.md

Cheers;

-Wayne
