### ISSUE TITLE
Why not use the array?

### ISSUE THREAD

**Issue by nickqiao** [waynewbishop/SwiftStructures#57]
In the Stack,you use the LLNode,why not use the array? I think if you use array,you can take advantage of many methods that Array provides,for example :remove  and count(<T>)....,maybe you have your ideas.

In EKAlgorithms,when the author implements the stack,he take advantage  of the NSMutableArray. When others read the code,very clear. But I see your stack implementation, it is more like C style.

So i hope your advice and your ideas.

thank you!

**Comment by waynewbishop** [comment]
Hi Nick;

Thanks for your question. At the time of the writing, it seemed to have greater educational value to implement the stack using another custom data structure. As a result, readers see how custom structures can be used to build a solution. In addition, both stacks and linked lists are discussed in [the book](http://shop.waynewbishop.com). 

The implementation for [Dijkstra's algorithm](https://github.com/waynewbishop/SwiftStructures/blob/master/Source/Factories/Graph.swift) also follows a similar pattern. If you have any further questions just let me know.
