### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by cmoulton** [waynewbishop/SwiftStructures#58]
In the Usage section of the wiki the link to http://waynewbishop.com/swift/ doesn't link to the correct URL.

**Comment by waynewbishop** [comment]
Hi Christina, thanks for pointing this out! Someone else also noticed this and submitted a <a href="https://github.com/waynewbishop/SwiftStructures/pull/59">pull request</a>. If you see anything else that should be updated just me know.
