### ISSUE TITLE
Refactor Merge Sort Algorithm

### ISSUE THREAD

**Issue by waynewbishop** [waynewbishop/SwiftStructures#61]
We currently have a <a href="https://github.com/waynewbishop/SwiftStructures/blob/master/Source/Factories/Sorting.swift" target="_blank"> merge sort</a> algorithm in our repo, but I feel this could be refactored into a more efficient / simplified model. The resulting code would be published in essay format.

**Comment by kaandedeoglu** [comment]
Here's a recursive version I did. I'm not sure if it's more efficient though

https://gist.github.com/kaandedeoglu/14a11230edafe8dacf67

**Comment by Dimentar** [comment]
Merge Method -> Original from "CLRS"

https://gist.github.com/Dimentar/adcebabe147fede490e5

**Comment by Dimentar** [comment]
Added another version not so performed like first, but less code.
However the running time for **10.000** items is **0.6 sec** around

https://gist.github.com/Dimentar/2ee38227cbdd82d4c065

**Comment by ulidev** [comment]
Hey guys, for compare the time between two functions and know what is more efficient, I did a library for this. https://github.com/ulidev/Zilean

I hope to help.
