### ISSUE TITLE
Trie Update for Swift 2.0

### ISSUE THREAD

**Issue by rmoffett** [waynewbishop/SwiftStructures#70]
I was trying to use the Trie code and the following had an error.

`let searchKey: String = keyword.substringToIndex(current.level + 1)` can't convert `Int` to `Index`

Fix it by casting to NSString
`let searchKey: String = (keyword as NSString).substringToIndex(current.level + 1)`

Also `keyword.length` becomes `keyword.characters.count`

**Comment by waynewbishop** [comment]
Hi Richard;

Thanks for sending this along. Just upgraded to Xcode 7.1 / Swift 2.1 but am not seeing the error you've described. In the recent code update to Swift 2, we did make a number of changes the [extensions](https://github.com/waynewbishop/SwiftStructures/blob/master/Source/Structures/extensions.swift). If you could triple check and ensure you're running the latest code version that would be great.

Thanks;

**Comment by rmoffett** [comment]
All is good now..

**Comment by waynewbishop** [comment]
Sounds good. If you're interested, feel free to download a copy of the [supporting book](http://shop.waynewbishop.com) this weekend as everything is 50% off! Cheers.

**Comment by rmoffett** [comment]
Question if you will... Why in `func findWord(keyword: String) -> Array<String>!` is the return type a forced unwrapped optional? Then further why is the 'var wordList: Array<String>! = Array<String>()` explicitly typed as a forced unwrapped optional if you are instantiating it as an empty Array?

**Comment by waynewbishop** [comment]
Hi Richard, thanks for the update. I usually like to declare return types as <i>unwrapped optionals</i>. While it doesn't make use of the standard `if..let` syntax, it does allow me to directly check for `nil` which works well when others are learning things from a Java / C# perspective. See `TrieTest.swift` for details. 

Your other question about `wordList` is a valid. I've removed the punctuation so this now acts as a standard (non nil) variable. This code update will be pushed to `master` with the next update. Thanks!
