### ISSUE TITLE
Binary search should have condition to exit if the item doesn't exist in the array.

### ISSUE THREAD

**Issue by kNeerajPro** [waynewbishop/SwiftStructures#75]
I have added a condition in the algorithm - 
func binarySearch(key:Int, imin: Int, imax:Int) {
    let midIndex = (imin + imax) / 2
    let midNumber = numberList[midIndex]
   // Exit condition if the item doesn't exist in the array. 
   if (imin > imax) {
        println("not found")
        return
    }
    if (midNumber > key) {
       newBinarySearch(key, imin, midIndex - 1)
    }
    else if (midNumber < key) {
        newBinarySearch(key, midIndex + 1, imax)
    }
    else {
        println("value found at index : \(midIndex)")
    }
}

**Comment by waynewbishop** [comment]
Hi Neera;

Thanks for your question. Binary Search, along with some other key algorithms have been refactored. The latest updates also include your question about a conditional exit. To see the change summary visit:

https://github.com/waynewbishop/SwiftStructures/releases/tag/v.2.1

Thanks;

-Wayne
