### ISSUE TITLE
Small typo on Linked Lists web page

### ISSUE THREAD

**Issue by ChrisSukhram** [waynewbishop/SwiftStructures#93]
There is a small type on the "http://waynewbishop.com/swift/linked-lists/" page in the code section for "adding links":

private var head: LLNode<T> LLNode<T>()

should be:

private var head: LLNode<T> **=** LLNode<T>()

**Comment by waynewbishop** [comment]
Thanks @ChrisSukhram for sending along this issue! This bug has been since resolved.
